server:
  port: 8082

spring:
  application:
    name: department-service
  datasource:
    url: jdbc:postgresql://postgresdb-department:5432/department_db
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: department_db

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:9001/eureka/