server:
  port: 8081

spring:
  application:
    name: employee-service
  config:
    import: "optional:configserver:http://config-service:9002"
  cloud:
    config:
      name: employee
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:9001/eureka/