server:
  port: 8083

spring:
  application:
    name: organization-service
  datasource:
    url: jdbc:oracle:thin:@oracledb-organization:1521:ORCLCDB
    username: SYS as SYSDBA
    password: Samit!=377040
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        default_schema: ORCLCDB

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:9001/eureka/